branch-defaults:
  master:
    environment: schools-dev
    group_suffix: null
global:
  application_name: schools
  default_ec2_keyname: deployers
  default_platform: Docker 1.11.1
  default_region: sa-east-1
  profile: null
  sc: git
